name: expect_emits_nothing
description: A utility to test that a stream emits no values.
version: 1.0.0
homepage: https://github.com/pitriq/expect_emits_nothing

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  test: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
